pressure_command_sender_node:
  ros__parameters:
    # Serial communication settings
    serial_port: "/dev/ttyUSB0"
    baud_rate: 2000000
    
    # Command transmission settings
    command_delay_ms: 100
    continuous_mode: true
    
    # Board configuration - matches reference code sequence
    board_ids: [12, 11, 10]  # 0x0C, 0x0B, 0x0A
    
    # Frame ID for published messages
    frame_id: "pressure_command"